services:
  apisix:
    image: apache/apisix:latest
    container_name: apisix
    ports:
      - "9080:9080"
      - "9180:9180"
    environment:
      - ADMIN_API_PASSWORD=admin
    volumes:
      - ./apisix-config:/apisix/conf
  
  gateway:
    image: openfaas/gateway:t6  # Update to latest available version
    container_name: openfaas-gateway
    ports:
      - "8080:8080"
    environment:
      - basic_auth=true
      - secret_mount_path=/run/secrets
      - function_namespace=openfaas-fn
    volumes:
      - ./gateway-config:/gateway/config
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
